# Generated by Django 4.2.4 on 2023-09-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('data_json', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('draft', models.JSONField(blank=True, null=True)),
                ('comments_url', models.URLField()),
                ('comments', models.PositiveIntegerField()),
                ('html_url', models.URLField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('repository_url', models.URLField()),
                ('timeline_url', models.URLField()),
                ('state', models.CharField(max_length=50)),
                ('reactions', models.JSONField()),
                ('performed_via_github_app', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('assignee', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('state_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('locked', models.BooleanField()),
                ('labels', models.JSONField()),
                ('milestone', models.CharField(blank=True, max_length=200, null=True)),
                ('labels_url', models.URLField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('node_id', models.CharField(max_length=100)),
                ('author_association', models.CharField(max_length=50)),
                ('pull_request', models.JSONField(blank=True, null=True)),
                ('user', models.JSONField()),
                ('active_lock_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('assignees', models.JSONField()),
                ('events_url', models.URLField()),
                ('url', models.URLField()),
            ],
        ),
    ]
