# Generated by Django 4.2.4 on 2023-09-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_issue_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('color', models.CharField(max_length=6)),
                ('data_json', models.JSONField(blank=True, null=True)),
                ('default', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('node_id', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
